// Scheduled briefs — a durable cron that asks the Brain (the PA persona, the same
// entry the PA chat route uses) to produce a periodic operations brief, then files
// it as a DRAFT proposal for a human to read/act on.
//
// Trigger: weekly cron, Monday 08:00 Europe/London.
//
// SAFETY — DRAFT ONLY. We call `runPaTurn` (read/summary intent) and persist the
// resulting text as a proposal via saveProposal. We never approve or execute
// anything: the brief is an artifact in the Approvals queue, nothing more. If the
// Brain is disabled (HERMES_BRAIN_ENABLED off) the run records a skip and exits.
//
// IDEMPOTENCY: the run is keyed by ISO week so a replay files at most one brief
// per week. The saveProposal call is wrapped in a named step so a retry re-uses
// the memoized proposal id rather than drafting a duplicate.
import { inngest, type StepLike } from '@/lib/inngest/client';
import { runPaTurn } from '@/lib/hermes/brain/graph';
import { saveProposal } from '@/lib/hermes/proposals';

const BRIEF_PROMPT =
  'Produce this week\'s operations brief for the estate: summarise open incidents, ' +
  'deploy/CI health, notable tickets, and anything that needs my attention. Keep it ' +
  'to a short scannable bullet list. Do not take any action — this is a read-only summary.';

// Deterministic ISO-week key so the brief is one-per-week even across replays.
function isoWeekKey(d = new Date()): string {
  const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
  const dayNum = (date.getUTCDay() + 6) % 7;
  date.setUTCDate(date.getUTCDate() - dayNum + 3);
  const firstThursday = new Date(Date.UTC(date.getUTCFullYear(), 0, 4));
  const week =
    1 +
    Math.round(
      ((date.getTime() - firstThursday.getTime()) / 86400000 -
        3 +
        ((firstThursday.getUTCDay() + 6) % 7)) /
        7,
    );
  return `${date.getUTCFullYear()}-W${String(week).padStart(2, '0')}`;
}

export async function scheduledBriefsHandler({
  step,
}: {
  step: Pick<StepLike, 'run'>;
}): Promise<{ week: string; status: string; proposalId?: string | null }> {
  const week = isoWeekKey();
  const threadId = `brief:${week}`;

  // Ask the Brain for the brief. runPaTurn is disabled-safe (returns
  // {status:'disabled'} when HERMES_BRAIN_ENABLED is off) and never throws.
  const turn = await step.run(`generate-brief-${week}`, async () =>
    runPaTurn({ threadId, message: BRIEF_PROMPT, persona: 'pa', actor: 'inngest:scheduled-briefs' }),
  );

  if (turn.status === 'disabled') {
    return { week, status: 'skipped-brain-disabled' };
  }
  if (turn.status === 'error') {
    return { week, status: `error:${turn.error}` };
  }

  const reply = 'reply' in turn ? turn.reply : '';
  const proposalId = await step.run(`file-brief-${week}`, async () =>
    saveProposal({
      ref: threadId,
      agent: 'pa',
      kind: 'brief',
      title: `Weekly operations brief — ${week}`,
      summary: `Automated weekly brief for ${week}. Review in the queue.`,
      proposal: {
        ok: true,
        configured: true,
        classification: `Scheduled brief · ${week}`,
        draft: reply || '(the Brain returned an empty brief)',
        reasoning: 'Weekly cron brief generated by the PA. Read-only — no action attached.',
      },
    }),
  );

  return { week, status: 'filed', proposalId };
}

export const scheduledBriefs = inngest.createFunction(
  {
    id: 'scheduled-weekly-brief',
    name: 'Scheduled — weekly operations brief',
    // Monday 08:00 Europe/London. Inngest supports a TZ= prefix on cron expressions.
    triggers: [{ cron: 'TZ=Europe/London 0 8 * * 1' }],
  },
  async ({ step }) => scheduledBriefsHandler({ step }),
);
