// Hermes · KB Auto-Authoring — ARTICLE DRAFT.
//
// Turns a detected gap (gaps.ts) into a reviewable help-centre article: title,
// summary, a markdown body, a suggested slug + category. Two modes with the SAME
// return shape:
//
//   1. DETERMINISTIC SKELETON (default / fail-safe) — assembled purely from the
//      example tickets' questions + resolutions. No model call, so it works with
//      the Brain off, no API key, and in unit tests.
//   2. LLM-AUTHORED BODY — only when brainEnabled() (HERMES_BRAIN_ENABLED) AND a
//      provider key is configured. The model is asked to write the body GROUNDED
//      strictly in the supplied resolutions (do not invent). Any failure (no key,
//      bad JSON, network) falls back to the skeleton — never throws.
//
// This module NEVER publishes. It does not write to content/kb or hermes.kb_chunks
// and does not save a proposal. It returns a DraftedArticle the caller can preview
// and, on human action, hand to saveProposal(kind:'kb-article') for approval.

import { brainEnabled } from '@/lib/hermes/brain/flags';

export type DraftExample = {
  ref: string;
  title: string;
  question: string;
  /** How the ticket was actually resolved (last reply/update). Grounds the body. */
  resolution?: string | null;
};

export type DraftInput = {
  theme: string;
  suggestedTitle: string;
  examples: DraftExample[];
};

export type KbCategory = 'Technical' | 'Billing' | 'Onboarding' | 'Security';

export type DraftedArticle = {
  title: string;
  summary: string;
  bodyMarkdown: string;
  slug: string;
  category: KbCategory;
  /** Which path produced the body — 'skeleton' (deterministic) or 'llm'. */
  source: 'skeleton' | 'llm';
  /** Model id when source==='llm'. */
  model?: string;
};

export type DraftOptions = {
  /** Force the LLM path on/off. Defaults to brainEnabled(). */
  useLlm?: boolean;
};

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64) || 'untitled';
}

// Deterministic category from the gap's language — matches the KB's four buckets
// (see app/v2/kb/[slug]/page.tsx). Keyword-driven, no model.
export function categorize(input: DraftInput): KbCategory {
  const hay = `${input.theme} ${input.suggestedTitle} ${input.examples
    .map((e) => e.question)
    .join(' ')}`.toLowerCase();
  const has = (...ks: string[]) => ks.some((k) => hay.includes(k));
  if (has('invoice', 'payment', 'billing', 'refund', 'charge', 'proration', 'subscription', 'dunning', 'card', 'plan', 'credit'))
    return 'Billing';
  if (has('login', 'sign in', 'sign-in', 'sso', 'saml', '2fa', 'mfa', 'oauth', 'password', 'security', 'breach', 'leak', 'token', 'permission'))
    return 'Security';
  if (has('invite', 'onboard', 'seat', 'teammate', 'member', 'organization', 'organisation', 'provision', 'getting started', 'setup'))
    return 'Onboarding';
  return 'Technical';
}

function cleanResolution(r?: string | null): string | null {
  const t = (r ?? '').trim();
  return t.length > 0 ? t : null;
}

// ---------------------------------------------------------------------------
// Deterministic skeleton — always available.
// ---------------------------------------------------------------------------
function skeletonBody(input: DraftInput, title: string): string {
  const questions = input.examples
    .map((e) => `- ${e.question || e.title} _(from ${e.ref})_`)
    .join('\n');

  const resolutions = input.examples
    .map((e) => ({ ref: e.ref, res: cleanResolution(e.resolution) }))
    .filter((x): x is { ref: string; res: string } => x.res != null);

  const resolutionBlock = resolutions.length
    ? resolutions.map((x) => `- **${x.ref}:** ${x.res}`).join('\n')
    : '_No resolution notes were recorded on the source tickets. Document the confirmed fix steps here before publishing._';

  const related = input.examples.map((e) => `- ${e.ref} — ${e.title}`).join('\n');

  return [
    `# ${title}`,
    '',
    `Customers repeatedly reached support about **${input.theme}** and no knowledge-base article covered it. This draft was auto-assembled from ${input.examples.length} resolved ticket(s) so the answer can be self-served next time.`,
    '',
    '## The question',
    questions || '- _(no example questions captured)_',
    '',
    '## Resolution',
    resolutionBlock,
    '',
    '## Related tickets',
    related || '- _(none)_',
    '',
    '---',
    `> Draft generated by Hermes KB Auto-Authoring from ${input.examples.length} resolved ticket(s). Review and edit before publishing — nothing here is live until a human approves it.`,
    '',
  ].join('\n');
}

function skeletonSummary(input: DraftInput): string {
  return `How to resolve "${input.theme}" — drafted from ${input.examples.length} resolved support ticket(s).`;
}

function buildSkeleton(input: DraftInput): DraftedArticle {
  const title = input.suggestedTitle.trim() || `How to handle ${input.theme}`;
  return {
    title,
    summary: skeletonSummary(input),
    bodyMarkdown: skeletonBody(input, title),
    slug: slugify(title),
    category: categorize(input),
    source: 'skeleton',
  };
}

// ---------------------------------------------------------------------------
// LLM-authored body — gated behind brainEnabled() + a configured key.
// ---------------------------------------------------------------------------
function extractJson(raw: string): any | null {
  const start = raw.indexOf('{');
  const end = raw.lastIndexOf('}');
  if (start === -1 || end === -1 || end < start) return null;
  try {
    return JSON.parse(raw.slice(start, end + 1));
  } catch {
    return null;
  }
}

async function llmDraft(input: DraftInput): Promise<DraftedArticle | null> {
  // Dynamic import keeps the server-only model module out of the default
  // (skeleton) path and out of the brain-off unit-test surface entirely.
  const { callModel } = await import('@/lib/hermes/brain/model');

  const grounding = input.examples
    .map((e, i) => {
      const res = cleanResolution(e.resolution);
      return [
        `Ticket ${i + 1} (${e.ref}):`,
        `  Question: ${e.question || e.title}`,
        `  Resolution: ${res ?? '(no resolution recorded)'}`,
      ].join('\n');
    })
    .join('\n\n');

  const system = [
    'You are a technical writer drafting a help-centre article for a SaaS support knowledge base.',
    'You write ONLY from the resolved support tickets provided — never invent product behaviour, prices, endpoints, or steps that are not in the resolutions.',
    'If the resolutions are thin, keep the article short and add a clearly-marked "To confirm" note rather than fabricating detail.',
    'Return STRICT JSON only, no prose or code fences, with exactly these keys:',
    '{ "title": string, "summary": string, "body": string (markdown), "category": one of "Technical"|"Billing"|"Onboarding"|"Security" }',
  ].join('\n');

  const user = [
    `Theme: ${input.theme}`,
    `Suggested title: ${input.suggestedTitle}`,
    '',
    'Resolved tickets to base the article on:',
    grounding,
  ].join('\n');

  const result = await callModel({
    messages: [
      { role: 'system', content: system },
      { role: 'user', content: user },
    ],
    temperature: 0.2,
    maxTokens: 1100,
  });

  if (!result.ok) return null;
  const parsed = extractJson(result.content ?? '');
  if (!parsed || typeof parsed.body !== 'string' || parsed.body.trim().length === 0) return null;

  const title =
    typeof parsed.title === 'string' && parsed.title.trim()
      ? parsed.title.trim()
      : input.suggestedTitle;
  const category: KbCategory =
    parsed.category === 'Billing' || parsed.category === 'Onboarding' || parsed.category === 'Security'
      ? parsed.category
      : parsed.category === 'Technical'
        ? 'Technical'
        : categorize(input);

  return {
    title,
    summary:
      typeof parsed.summary === 'string' && parsed.summary.trim()
        ? parsed.summary.trim()
        : skeletonSummary(input),
    bodyMarkdown: parsed.body.trim(),
    slug: slugify(title),
    category,
    source: 'llm',
    model: result.model,
  };
}

/**
 * Draft a help-centre article for a gap. Returns a deterministic skeleton unless
 * the LLM path is enabled AND succeeds. Never publishes; never throws.
 */
export async function draftArticle(
  input: DraftInput,
  opts: DraftOptions = {},
): Promise<DraftedArticle> {
  const useLlm = opts.useLlm ?? brainEnabled();
  if (useLlm) {
    try {
      const drafted = await llmDraft(input);
      if (drafted) return drafted;
    } catch {
      // fall through to the deterministic skeleton
    }
  }
  return buildSkeleton(input);
}
